<script lang="ts">
	import { scaleLinear } from 'd3-scale';
	import type { PageData } from './$types';
	export let data: PageData;
	// let data=dedom.body.lines;
	const d = data.body.lines;
	const prompt=data.body.prompt;

	const timePeriods: String[] = [];
	
	
	// find num of timeperiods
	let maxTimePeriods = 0;
	try{
		maxTimePeriods = Math.max(...d.map((person) => person.data.length));
	}
	catch (e){
		console.log(e);
	}

	// scan d and for its length do something

	let year = 22;
	for (let i = 0; i < maxTimePeriods; i++) {
		if (i % 2 == 0) {
			let str = 'Μαρ ' + year.toString();
			timePeriods.push(str);
		} else {
			let str = 'Σεπ ' + year.toString();
			timePeriods.push(str);
			year++;
		}
	}
	console.log(d);
	const xTicks = d.map((person) => person.name);
	const yTicks = [0, 1, 2];
	const padding = { top: 20, right: 15, bottom: 20, left: 60 };

	let width = 500;
	let height = 200;

	$: xScale = scaleLinear()
		.domain([0, d.length])
		.range([padding.left, width - padding.right]);

	$: innerWidth = width - (padding.left + padding.right);
	$: barWidth = innerWidth / xTicks.length;
	function getBarHeight(person: any) {
		const zeroIndex = person.data.indexOf(0);
		const lastIndex = zeroIndex === -1 ? person.data.length : zeroIndex;
		return yScale(lastIndex);
	}
	// Calculate the maximum number of time periods
	$: maxTimePeriods = Math.max(...d.map((person) => person.data.length));

	// Update the yScale domain to reflect the maximum number of time periods
	$: yScale = scaleLinear()
		.domain([0, maxTimePeriods])
		.range([height - padding.bottom, padding.top]);
</script>

<div class="container my-10 grid place-items-center pt-6 text-center content-center overflow-auto scrollbar-hide">
	<div class="col-1-1">
		<h1>Spotify Family Pay Data</h1>
	</div>
	<h4 class="pt-10 mb-10">{prompt} <sup>1</sup></h4>

	<div class="chart" bind:clientWidth={width} bind:clientHeight={height}>
		<svg viewBox="0 0 400 200" preserveAspectRatio="xMidYMid meet">
			<!-- x axis -->
			<g class="axis x-axis">
				{#each d as person, i}
					<g class="tick" transform="translate({xScale(i)},{height})">
						<text x={barWidth / 2} y="-4">{person.name}</text>
					</g>
				{/each}
			</g>

			<g class="bars">
				{#each d as person, i}
					<rect
						x={xScale(i) + 2}
						y={getBarHeight(person)}
						width={barWidth - 4}
						height={yScale(0) - getBarHeight(person)}
					/>
					
				{/each}
				<!-- create blank dotted line above -->
			</g>
			<g class="time-periods">
				{#each timePeriods as period, i}
					<!-- <text x="0" y="{yScale(i)}" >{period}</text> -->
					<text x={padding.left - 45} y={yScale(i)} dy=".35em">{period}</text>
				
					<!-- create dotted line below -->
					 <line x1={50} y1={yScale(i)} x2={width} y2={yScale(i)} stroke="white" stroke-width="1" stroke-dasharray="3,3" />

				{/each}
			</g>
		</svg>
	</div>

	<a href="https://revolut.me/angelokyn" target="_blank" rel="noopener noreferrer" class="rounded-full btn my-10 variant-filled btn-animate">
		<!-- image with src rev.png -->
		<img src="https://www.logo.wine/a/logo/Revolut/Revolut-Icon-Logo.wine.svg" alt="Icon" class="h-12 w-12 inline mr-2">
		<span>Πλερώ<sup>2</sup></span>
	</a> 

	<!-- add an image from this location "static/7j3lph.jpg" -->
	<img src="/meme.jpg" alt="meme" class="h-90 w-90 mx-auto my-5">
</div>
<footer class="footer absolute inset-x-0 bottom-0 py-0 bg-gray-500 bg-opacity-90 text-white content-center">
	<div class="container text-center text-sm">
	  Made with love using
	  <a href="https://www.skeleton.dev/" target="_blank" rel="noopener noreferrer" class="text-blue-400 hover:text-blue-600">
		Skeleton UI
	  </a>
	  and
	  <a href="https://kit.svelte.dev/" target="_blank" rel="noopener noreferrer" class="text-blue-400 hover:text-blue-600">
		SvelteKit
	  </a><br>
	  <span class="text-center inset-x-0 text-xs">1. Prompts are randomly generated by ChatGPT.<br>2. Payment costs 13€ per 6 months (as of September 2023).
	  </span>
	</div>

	
  </footer>
<style>
	.chart {
		/* width: 100%; */
		max-width: flex;
		margin: 0 auto;
	}

	svg {
		flex: auto;
		width: 100%;
		height: 200px;
	}

	.tick {
		font-family: Helvetica, Arial;
		font-size: 0.725em;
		font-weight: 600;
		color: #ccc;
	}

	.time-periods {
    font-family: Helvetica, Arial;
    font-size: 0.725em;
    font-weight: 600;
    fill: #ffffff;
}
	sup{
		font-size: 0.55em;
	}
	.tick text {
		fill: #ccc;
		text-anchor: start;
	}

	.x-axis .tick text {
		text-anchor: middle;
	}

	.bars rect {
		fill: rgb(128, 37, 48);
		stroke: none;
		opacity: 0.65;
	}
	.btn:hover {
  background-color: #1c6ef2;
  color: #fff;
  transform: scale(1.1);
  transition: all 0.3s ease-in-out;
}
	.btn-animate {
  position: relative;
  animation: fadeInTranslate 1s ease-in-out;
}

@keyframes fadeInTranslate {
  0% {
    opacity: 0;
    transform: translateY(-50%);
	transform: translateX(-50%);
  }
  100% {
    opacity: 1;
    transform: translateY(0);
	transform: translateX(0);
  }
}
</style>